// ------------------------------------------------------------
// autofix.js — Interactive Auto-Fix Engine (Redirects, JSON, Dead Feeds)
// ------------------------------------------------------------
//
// Responsibilities:
//   - Prompt user interactively for each problematic feed
//   - Arrow-key UI (no dependencies)
//   - Fix redirect URLs
//   - Fix JSON feed types
//   - Handle dead feeds:
//       * Remove
//       * Replace URL
//       * Move to dead_feeds
//       * Skip
//   - Write updated FEEDS maps to backend + frontend
//   - Create timestamped backups
// ------------------------------------------------------------

const fs = require("fs");
const path = require("path");
const readline = require("readline");
const {
  color,
  success,
  error,
  warning,
  info,
  highlight,
  menuItem,
} = require("../utils/colors");

// ------------------------------------------------------------
// Arrow-key interactive menu
// ------------------------------------------------------------

function promptMenu(question, choices) {
  return new Promise((resolve) => {
    console.log(info(`\n${question}\n`));

    let index = 0;

    function render() {
      process.stdout.write("\x1b[2K\r"); // clear line
      console.log(""); // spacing
      choices.forEach((choice, i) => {
        if (i === index) {
          console.log("  " + highlight(choice));
        } else {
          console.log("  " + menuItem(choice));
        }
      });
      console.log(""); // spacing
    }

    render();

    process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.setEncoding("utf8");

    function onKeypress(key) {
      if (key === "\u0003") {
        // Ctrl+C
        process.exit();
      }

      if (key === "\u001b[A") {
        // Up arrow
        index = (index - 1 + choices.length) % choices.length;
        render();
      } else if (key === "\u001b[B") {
        // Down arrow
        index = (index + 1) % choices.length;
        render();
      } else if (key === "\r") {
        // Enter
        process.stdin.setRawMode(false);
        process.stdin.pause();
        process.stdin.removeListener("data", onKeypress);
        resolve(choices[index]);
      }
    }

    process.stdin.on("data", onKeypress);
  });
}

// ------------------------------------------------------------
// Prompt for text input (URL replacement)
// ------------------------------------------------------------

function promptInput(question) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    rl.question(info(question + " "), (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

// ------------------------------------------------------------
// Backup writer
// ------------------------------------------------------------

function writeBackup(filePath, content) {
  const dir = path.dirname(filePath);
  const base = path.basename(filePath, ".js");
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = path.join(dir, `${base}.backup.${timestamp}.js`);

  fs.writeFileSync(backupPath, content, "utf8");
  console.log(warning(`   ↪ Backup created: ${backupPath}`));
}

// ------------------------------------------------------------
// FEEDS map writer (backend + frontend)
// ------------------------------------------------------------

function writeFeedsMap(filePath, feedsObj) {
  const content =
    "// Auto-generated by auto-fix engine\nmodule.exports = {\n  FEEDS: " +
    JSON.stringify(feedsObj, null, 2) +
    "\n};\n";

  writeBackup(filePath, fs.readFileSync(filePath, "utf8"));
  fs.writeFileSync(filePath, content, "utf8");
  console.log(success(`   ✔ Updated FEEDS map: ${filePath}`));
}

// ------------------------------------------------------------
// Main auto-fix engine
// ------------------------------------------------------------

async function runAutoFix(backendPath, frontendPath, backendFeeds, networkResults) {
  console.log(info("\n[AUTOFIX] Starting auto-fix mode...\n"));

  // Clone feeds so we can mutate safely
  const updated = JSON.parse(JSON.stringify(backendFeeds));

  for (const result of networkResults) {
    const { category, feedId, originalUrl, finalUrl, health, kind, reason } = result;

    // Skip healthy feeds
    if (health === "healthy") continue;

    console.log(warning(`\n⚠ Feed requires attention: ${feedId} (${category})`));
    console.log(`   Health: ${health}`);
    console.log(`   Reason: ${reason}`);
    console.log(`   Original URL: ${originalUrl}`);
    console.log(`   Final URL: ${finalUrl}`);

    // ------------------------------------------------------------
    // Redirect fix
    // ------------------------------------------------------------
    if (health === "redirect" && finalUrl !== originalUrl) {
      const choice = await promptMenu(
        `Feed "${feedId}" was redirected.\nApply redirect fix?`,
        ["Apply redirect", "Skip"]
      );

      if (choice === "Apply redirect") {
        updated[category] = updated[category].map((f) =>
          f.id === feedId ? { ...f, url: finalUrl } : f
        );
        console.log(success(`   ✔ Updated URL to: ${finalUrl}`));
      }

      continue;
    }

    // ------------------------------------------------------------
    // JSON feed fix
    // ------------------------------------------------------------
    if (kind === "json" && health === "healthy") {
      const choice = await promptMenu(
        `Feed "${feedId}" is JSON.\nUpdate type to "json"?`,
        ["Update type", "Skip"]
      );

      if (choice === "Update type") {
        updated[category] = updated[category].map((f) =>
          f.id === feedId ? { ...f, type: "json" } : f
        );
        console.log(success(`   ✔ Updated type to JSON`));
      }

      continue;
    }

    // ------------------------------------------------------------
    // Dead feed handling
    // ------------------------------------------------------------
    if (health === "dead" || health === "html_error" || health === "blocked") {
      const choice = await promptMenu(
        `Feed "${feedId}" appears dead or invalid.\nChoose an action:`,
        [
          "Remove feed",
          "Move to dead_feeds",
          "Replace URL",
          "Skip",
        ]
      );

      if (choice === "Remove feed") {
        updated[category] = updated[category].filter((f) => f.id !== feedId);
        console.log(error(`   ✘ Removed feed: ${feedId}`));
      }

      if (choice === "Move to dead_feeds") {
        updated.dead_feeds = updated.dead_feeds || [];
        updated.dead_feeds.push({
          id: feedId,
          url: originalUrl,
          type: kind,
          reason,
          originalCategory: category,
        });
        updated[category] = updated[category].filter((f) => f.id !== feedId);
        console.log(warning(`   ↪ Moved to dead_feeds`));
      }

      if (choice === "Replace URL") {
        const newUrl = await promptInput("Enter new URL:");
        updated[category] = updated[category].map((f) =>
          f.id === feedId ? { ...f, url: newUrl } : f
        );
        console.log(success(`   ✔ Updated URL to: ${newUrl}`));
      }

      continue;
    }
  }

  // ------------------------------------------------------------
  // Write updated maps
  // ------------------------------------------------------------
  console.log(info("\n[AUTOFIX] Writing updated FEEDS maps...\n"));

  writeFeedsMap(backendPath, updated);
  writeFeedsMap(frontendPath, updated);

  console.log(success("\n[AUTOFIX] Auto-fix complete.\n"));

  return updated;
}

module.exports = {
  runAutoFix,
};
